### ISSUE TITLE
No diff for deleted files?

### ISSUE THREAD

**Issue by dashmug** [softprops/diffset#33]
First of all, thank you for creating and maintaining this action. This has saved a lot of build time (and money).

I have run across an example where this Github action caused steps to be skipped when they shouldn't be.

I have a repo containing both Python and Javascript files. My workflow uses this Github action to see if there are changes to Python files in order to run Python CI steps and same for Javascript files.

I found that deleting files only (no additions, no updates) were not detected by this Github action.

```yaml
    steps:
      - uses: actions/checkout@v4.1.7
        with:
          fetch-depth: 0
      - name: Check for changed files
        if: github.ref != 'refs/heads/main'
        id: diffset
        uses: softprops/diffset@v2.1.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          base: main
          backend_files: |
            backend/**/*.py
            backend/poetry.lock
            backend/pyproject.toml
      - name: Run backend CI
        if: github.ref == 'refs/heads/main' || steps.diffset.outputs.backend_files
        run: (my Python lint and test commands) 
```

In this incident, some python source files were deleted. It will fail the lint and test due to those missing modules. But in CI, these steps were skipped since ` steps.diffset.outputs.backend_files` is still false or empty despite the deleted `backend/**/*.py` files. I would have expected it to contain the list of deleted files as well.

Luckily, in our case since we don't skip steps in deployment, it was caught. It would have been nice if it failed during PR instead of after merging.
