### ISSUE TITLE
Unexpected input 'scala_files', valid inputs are ['base']

### ISSUE THREAD

**Issue by chenrui333** [softprops/diffset#5]
```
##[warning]Unexpected input 'scala_files', valid inputs are ['base']
##[warning]Unexpected input 'java_files', valid inputs are ['base']
##[warning]Unexpected input 'cfn_files', valid inputs are ['base']
Run softprops/diffset@v1
  with:
    scala_files: **/*.scala
    java_files: **/*.java
    cfn_files: **/*.cf.yml
  env:
    GITHUB_TOKEN: ***
```

Config

```
    steps:
      - name: Diffset
        id: diffset
        uses: softprops/diffset@v1
        with:
          scala_files: '**/*.scala'
          java_files: '**/*.java'
          cfn_files: '**/*.cf.yml'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

**Comment by softprops** [comment]
👋 beyond a warning are you seeing absent list of files?

The warning seems like a likely recent change to the GitHub runners, presumably in an attempt to make best effort inferences from [`action.yml`](https://help.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions) files more visible.

In the case of this action,  there is one declared statically named input named [`base`](https://github.com/softprops/diffset/blob/8320c0c4c0a484f48a69fe38b271476f1103f85f/action.yml#L10-L12) with the remainder dynamically named declarations of files sets, essentially to let you give name to a user defined set of prefiltered files that have changed.

If the warning is doing no harm I don't think there is an action to take. This feels like a limitation of action declaration properties at the moment.

If the warning is causing harm you can move from using inputs to direct env variables. Since `with` declaration are [short hand for environment variables prefixed with `INPUT_`](https://github.com/softprops/diffset/blob/8320c0c4c0a484f48a69fe38b271476f1103f85f/src/util.ts#L14-L15), you could if you wish leverage that knowledge to do something like this.

```yaml
      - name: Diffset
        id: diffset
        uses: softprops/diffset@v1
        env:
          INPUT_SCALA_FILES: '**/*.scala'
          INPUT_JAVA_FILES: '**/*.java'
          INPUT_CFN_FILES: '**/*.cf.yml'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

If there is not harm caused, I suspect the extra effort might be wasted.
